openapi: 3.0.3
info:
  title: DotAAS Part 2 | HTTP/REST | Registry and Discovery API
  description: The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
  contact:
    name: Michael Hoffmeister, Torben Miny, Andreas Orzelski, Manuel Sauer, Constantin Ziesche
  version: V1.0RC01
  termsOfService: https://github.com/admin-shell-io/aas-specs
paths:
  '/registry/shell-descriptors':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns all Asset Administration Shell Descriptors
      operationId: GetAllAssetAdministrationShellDescriptors
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAssetAdministrationShellDescriptors/1/0/RC02
      responses:
        "200":
          description: Requested Asset Administration Shell Descriptors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/AssetAdministrationShellDescriptor'
    post:
      tags:
      - Registry and Discovery Interface
      summary: Creates a new Asset Administration Shell Descriptor, i.e. registers an AAS
      operationId: PostAssetAdministrationShellDescriptor
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAssetAdministrationShellDescriptor/1/0/RC02
      requestBody:
        description: Asset Administration Shell Descriptor object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/AssetAdministrationShellDescriptor'
        required: true
      responses:
        "201":
          description: Asset Administration Shell Descriptor created successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/AssetAdministrationShellDescriptor'
  '/registry/shell-descriptors/{aasIdentifier}':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns a specific Asset Administration Shell Descriptor
      operationId: GetAssetAdministrationShellDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAssetAdministrationShellDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Requested Asset Administration Shell Descriptor
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/AssetAdministrationShellDescriptor'
    put:
      tags:
      - Registry and Discovery Interface
      summary: Updates an existing Asset Administration Shell Descriptor
      operationId: PutAssetAdministrationShellDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutAssetAdministrationShellDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Asset Administration Shell Descriptor object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/AssetAdministrationShellDescriptor'
        required: true
      responses:
        "204":
          description: Asset Administration Shell Descriptor updated successfully
    delete:
      tags:
      - Registry and Discovery Interface
      summary: Deletes an Asset Administration Shell Descriptor, i.e. de-registers an AAS
      operationId: DeleteAssetAdministrationShellDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteAssetAdministrationShellDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Asset Administration Shell Descriptor deleted successfully
  '/registry/shell-descriptors/{aasIdentifier}/submodel-descriptors':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns all Submodel Descriptors
      operationId: GetAllSubmodelDescriptors
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllSubmodelDescriptors/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Requested Submodel Descriptors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/SubmodelDescriptor'
    post:
      tags:
      - Registry and Discovery Interface
      summary: Creates a new Submodel Descriptor, i.e. registers a submodel
      operationId: PostSubmodelDescriptor
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostSubmodelDescriptor/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Submodel Descriptor object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/SubmodelDescriptor'
        required: true
      responses:
        "201":
          description: Submodel Descriptor created successfully
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/SubmodelDescriptor'
  '/registry/shell-descriptors/{aasIdentifier}/submodel-descriptors/{submodelIdentifier}':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns a specific Submodel Descriptor
      operationId: GetSubmodelDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetSubmodelDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: submodelIdentifier
        in: path
        description: The Submodel’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Requested Submodel Descriptor
          content:
            application/json:
              schema:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/SubmodelDescriptor'
    put:
      tags:
      - Registry and Discovery Interface
      summary: Updates an existing Submodel Descriptor
      operationId: PutSubmodelDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PutSubmodelDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: submodelIdentifier
        in: path
        description: The Submodel’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Submodel Descriptor object
        content:
          application/json:
            schema:
              $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/SubmodelDescriptor'
        required: true
      responses:
        "204":
          description: Submodel Descriptor updated successfully
    delete:
      tags:
      - Registry and Discovery Interface
      summary: Deletes a Submodel Descriptor, i.e. de-registers a submodel
      operationId: DeleteSubmodelDescriptorById
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteSubmodelDescriptorById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: submodelIdentifier
        in: path
        description: The Submodel’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Submodel Descriptor deleted successfully
  '/lookup/shells':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns a list of Asset Administration Shell ids based on Asset identifier key-value-pairs
      operationId: GetAllAssetAdministrationShellIdsByAssetLink
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAssetAdministrationShellIdsByAssetLink/1/0/RC02
      parameters:
      - name: assetIds
        in: query
        description: The key-value-pair of an Asset identifier
        required: false
        style: form
        explode: true
        schema:
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/IdentifierKeyValuePair'
          example: '[{"key": "globalAssetId","value": "http://example.company/myAsset"},{"key": "myOwnInternalAssetId","value": "12345ABC"}]'
      responses:
        "200":
          description: Requested Asset Administration Shell ids
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/Identifier'
  '/lookup/shells/{aasIdentifier}':
    get:
      tags:
      - Registry and Discovery Interface
      summary: Returns a list of Asset identifier key-value-pairs based on an Asset Administration Shell id to edit discoverable content
      operationId: GetAllAssetLinksById
      x-semanticIds:
        - https://admin-shell.io/aas/API/GetAllAssetLinksById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Requested Asset identifier key-value-pairs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/IdentifierKeyValuePair'
    post:
      tags:
      - Registry and Discovery Interface
      summary: Creates all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
      operationId: PostAllAssetLinksById
      x-semanticIds:
        - https://admin-shell.io/aas/API/PostAllAssetLinksById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Asset identifier key-value-pairs
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/IdentifierKeyValuePair'
        required: true
      responses:
        "201":
          description: Asset identifier key-value-pairs created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://api.swaggerhub.com/domains/Plattform_i40/Shared-Domain-Models/V1.0RC01#/components/schemas/IdentifierKeyValuePair'
    delete:
      tags:
      - Registry and Discovery Interface
      summary: Deletes all Asset identifier key-value-pair linked to an Asset Administration Shell to edit discoverable content
      operationId: DeleteAllAssetLinksById
      x-semanticIds:
        - https://admin-shell.io/aas/API/DeleteAllAssetLinksById/1/0/RC02
      parameters:
      - name: aasIdentifier
        in: path
        description: The Asset Administration Shell’s unique id (BASE64-URL-encoded)
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: Asset identifier key-value-pairs deleted successfully